Dz11
GoldaEV/CleanCodeProject pull request #1
Opened 2019-03-27 21:57 UTC by GoldaEV

2019-03-28 13:21 UTC, RomanKashenok approved these changes

2019-03-28 17:14 UTC, tim-teacher requested changes

2019-03-28 17:14 UTC, jushlwest commented on app/src/main/java/com/golda/cleancodeproject/presentation/screen/vehicle/list/VehicleListFragment.kt
> +    private lateinit var onVehicleClicked : OnVehicleClicked
Это ссылка на активити? зачем туда кидать клик если у нас есть общая ViewModel через которую можно отправить данные.

2019-03-28 19:06 UTC, GoldaEV commented on app/src/main/java/com/golda/cleancodeproject/presentation/screen/vehicle/list/VehicleListFragment.kt
> +    private lateinit var onVehicleClicked : OnVehicleClicked
Ок попробую переделать через ViewModel

2019-04-01 09:12 UTC, tim-teacher approved these changes
Апрув, несолько незначительных ошибок только

2019-04-01 09:12 UTC, jushlwest commented on app/src/main/java/com/golda/cleancodeproject/presentation/screen/vehicle/list/VehicleListFragment.kt
> +                recycleViewVehicle.hasFixedSize()
а где set?  recycleViewVehicle.hasFixedSize() вроди ж только возвращает значение.

2019-04-01 09:12 UTC, jushlwest commented on app/src/main/java/com/golda/cleancodeproject/presentation/screen/vehicle/list/adapter/CustomViewHolder.kt
> +        view.name_item.text = "${item.id}  ${item.fleetType}"
нижнее подчеркивание + для адаптеров лучше юзать findViewById вместе экстеншенов

2019-04-01 11:54 UTC, closed without merging